version: '3'
services:

  web:
    image: ghcr.io/graalvm/graalvm-ce:java11-21.3.0
    ports:
      - 8080:8080
      - 8000:8000
    env_file:
      - ./.env
    environment:
      MONGO_URL_FULL_STACK_ZIO: mongodb://root:secret@mongo:27017/admin
      DATABASE_URL_FULL_STACK_ZIO: jdbc:postgresql://postgres:5432/fullstackzio?user=root&password=secret
      JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=8000"
    links:
      - mongo
      - postgres
    depends_on:
      - mongo
      - postgres
    volumes:
    - ./target/universal/stage/:/home/full-stack-zio
    command: /home/full-stack-zio/bin/app

  mongo:
    image: mongo:3.6
    restart: always
    command: --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./cache/mongodata:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  # docker-compose run postgres bash
  # psql -h postgres -d fullstackzio -U root
  postgres:
    image: postgres:12.2
    ports:
     - "5432:5432"
    environment:
      POSTGRES_DB: fullstackzio
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
     - ./cache/postgres:/var/lib/postgresql/data

  # mkdir -p cache/pgadmin
  # chown -R 5050:5050 cache/pgadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
     - "8082:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - ./cache/pgadmin:/var/lib/pgadmin
